include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_return: warning
    unnecessary_cast: warning
    unnecessary_parenthesis: warning
    unnecessary_getters_setters: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_final_fields: warning
    prefer_is_not_empty: warning
    use_build_context_synchronously: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    camel_case_types: ignore