name: hmwssb
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 22.0.0+40

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  # appcheck: ^1.5.2
  device_info_plus: ^11.2.0
  dio: ^5.3.3
  # dropdown_search: ^0.5.0
  dropdown_search: ^6.0.1
  excel: ^4.0.3
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.3
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^6.1.5
  # webview_flutter: ^4.10.0
  # flutter_pdfview: ^1.3.2
  # flutter_pdfview: ^1.4.0
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.0
  group_button: ^5.0.1
  http: ^0.13.5
  image_picker: ^1.0.4
  internet_file: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.5.0
  map_picker: ^0.0.3
  number_to_indian_words: ^1.0.1
  open_file: ^3.5.10
  package_info_plus: ^8.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.1.0
  # path_provider: ^2.0.11
  pin_code_fields: ^8.0.1
  # pretty_dio_logger: ^1.3.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.0.9
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.2.4
  # url_launcher_ios: ^6.3.2
  # flutter_local_notifications: ^18.0.0
  # firebase_core: ^3.9.0
  # firebase_messaging: ^15.1.0
  # firebase_crashlytics: ^4.1.0
  sms_autofill: ^2.4.1
  safe_device: ^1.1.9
  screen_protector: ^1.4.2+1
  # sqflite: ^2.3.0

dependency_overrides:
  # url_launcher_ios: 6.2.4
  sqflite: 2.3.0
  # flutter_inappwebview_ios: 1.0.14
  # flutter_pdfview: 1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   sqflite: ^2.3.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - files/
    - assets/
    - assets/images/
    - assets/svg/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
