
  var meterMakeList = [
    "Chambal - NBDN Multijet",
    "Federal - FM104",
    "Hanbit -MIB15",
    "Ningbo water meter - Multi/MJ-SDC",
    "CRESCENT - CGM",
    "CRESCENT - CBM",
    "Darvesh - MJB",
    "Toshi - Multijet",
    "Rahul - Multijet",
    "Global - Multijet",
    "GlobalM - Multijet",
    "Globtech - Multijet",
    "Dasmesh - Multijet",
    "ZENNER - Multijet",
    "Konarak - Multijet"
  ];

  List<String> meterAgencies = [
    "M/s Bharath Precision Instruments co",
    "M/s Bharath Tech",
    "M/s Bharathi Engineering Works",
    "M/s Deccan Power Products Pvt Ltd",
    "M/s Dhanalaxmi enterprises",
    "M/s Fazal water meter sanitary works",
    "M/s G S Reddy Constructions",
    "M/s General water and meter and sanitary works",
    "M/s Habit Automation Technologies Pvt Ltd",
    "M/s Jangaiah electrical works",
    "M/s KVS and co",
    "M/s Kumar Electrical Works",
    "M/s Mantech Constructions",
    "M/s Om Sri Sai Water Meters",
    "M/s R.R Enterprises",
    "M/s R.V Utilities",
    "M/s RIRO Technologies",
    "M/s Sai Agencies",
    "M/s Sri Bhuvana Technologies",
    "M/s Sri Sainath Communications",
    "M/s Sri Shyam Enterprises",
    "M/s Srinivasa Engineering works",
    "M/s Storm energy Solutions Pvt Ltd",
    "M/s Saverly Technologies Private Ltd",
    "Others",
  ];

